<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="com.salle.test.funcionales.header.Test_HeaderTest" tests="1" time="15.922" ignored="0" failures="1" timestamp="10 Jan 2019 16:57:42 GMT" skipped="0" hostname="DESKTOP-BSD5S3P" errors="0">
  <testcase name="Header_Accesos" time="15.922" classname="com.salle.test.funcionales.header.Test_HeaderTest">
    <failure type="java.lang.AssertionError" message="expected [http://alumni.salleurl.edu/?_ga=2.123529227.1626555648.1547139439-1500646009.1547139439] but found [http://alumni.salleurl.edu/]">
      <![CDATA[java.lang.AssertionError: expected [http://alumni.salleurl.edu/?_ga=2.123529227.1626555648.1547139439-1500646009.1547139439] but found [http://alumni.salleurl.edu/]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at com.salle.tools.Esenciales.ValidaUrl(Esenciales.java:10)
	at com.salle.Steps.Steps_header.Step3_Entra_Alumni(Steps_header.java:96)
	at com.salle.test.funcionales.header.Test_HeaderTest.Header_Accesos(Test_HeaderTest.java:97)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- Header_Accesos -->
</testsuite> <!-- com.salle.test.funcionales.header.Test_HeaderTest -->
